# Assignment

Import numpy as np

In [1]:
import numpy as np

Make a python list => \[1,2,3,4,5\]

Convert it into numpy array and print it

In [2]:
li = [1,2,3,4,5]
li_np_arr = np.array(li)
print(li_np_arr)
# print(type(li_np_arr))

[1 2 3 4 5]


Make a python matrix (3 x 3) => \[[1,2,3],[4,5,6],[7,8,9]\]

Convert it into numpy array and print it

In [3]:
li2 = [[1,2,3],[4,5,6],[7,8,9]]
li2_np_arr = np.array(li2)
print(li2_np_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Make a matrix (3 x 3) using built-in methods (like arange(), reshape() etc.):

\[ [1,3,5],

 [7,9,11],
 
 [13,15,17] \]

In [70]:
arr_built = np.arange(1,18,2).reshape(3,3)
print(arr_built)

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]


Create a numpy array with 10 random numbers from 0 to 10 (there should be few numbers greater than 1)

In [118]:
ranarr1 = np.random.randint(0,10,10)
# ranarr1 = np.random.rand(10?
print(ranarr1)

[9 5 0 1 3 5 8 9 9 7]


Create numpy array => \[1,2,3,4,5\] and convert it to 2D array with 5 rows

In [85]:
arr2d = np.arange(1,6).reshape(5,1)

arr2d

array([[1],
       [2],
       [3],
       [4],
       [5]])

Print the shape of the above created array

In [86]:
arr2d.shape

(5, 1)

Create a numpy array with 10 elements in it. Access and print its 3rd, 4th and 9th element.

In [119]:
arr2 = np.arange(1,11)
print(arr2,"\n")
print(arr2[2],arr2[3],arr2[8])

[ 1  2  3  4  5  6  7  8  9 10] 

3 4 9


Print alternate elements of that array

In [120]:
print(arr2[::2])

[1 3 5 7 9]


Change last 3 elements into 100 using broadcasting and print

In [121]:
# arr2[7:10]=100
arr2 = [i//i*100 if i>=arr2[-3] else i for i in arr2]
print(arr2)

[1, 2, 3, 4, 5, 6, 7, 100, 100, 100]


Create a 5 x 5 matrix (fill it with any element you like), print it.

Then print the middle (3 x 3) matrix.

In [122]:
arr_five = np.arange(1,26).reshape(5,5)
# print(arr_five)
print(arr_five[1:4,1:4])

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]
